### ISSUE TITLE
Audio quality

### ISSUE THREAD

**Issue by dickyharper** [An0nimia/DeezloaderAn0n_bot#13]
Can I choose audio quality for downloading? 😞

**Comment by An0nimia** [comment]
@dickyharper You could, if you would read the messages which bot sends to you.

**Comment by An0nimia** [comment]
@dickyharper And let me to understand this for you is an issue? If someone has infos to ask, please contact me on Telegram, Gracias.

**Comment by dickyharper** [comment]
I'm really sorry for writing here.  I don't use Telegram yet.  I wanted to ask if this property exists.  Sorry again.

**Comment by An0nimia** [comment]
@dickyharper So you are saying me that you don't even tried the code before ask?

**Comment by dickyharper** [comment]
I asked a few places without asking here.  Nobody answered.  Sounds like a good idea to ask.  Sorry for the inconvenience. 😖
Best Regards.

**Comment by An0nimia** [comment]
@dickyharper Nada, don't worry.
