### ISSUE TITLE
Speed of bot

### ISSUE THREAD

**Issue by destroyer19991** [An0nimia/DeezloaderAn0n_bot#20]
There is a huge difference between the new code of deezloader and the old code. I deployed this new code and took around 1 hr for the same playlist of 50 songs which got downloaded in about 20 minutes in old bot. Both bots were tested on same server. Is it same for you is there anything that I am doing wrong . Please suggest something to fix this issue

**Comment by An0nimia** [comment]
@destroyer19991 Buy a better vps with better bandwidth the playlist download is always the same :)
