### ISSUE TITLE
quality settings and current release

### ISSUE THREAD

**Issue by K3nn3th2** [An0nimia/DeezloaderAn0n_bot#22]
hi!

i have a question regarding your awesome (!) bot.
is there a way to set the quality to a different value than MP3_320 ? (eg. FLAC?)

how can i run the latest version of your bot? i just started using it from within telegram (Music Hunters) and was wondering if i am automatically using the latest version, as i saw some buttons in this repository's code which i did not see in the teelgram bot.

thank!

**Comment by Mushebeq** [comment]
Read [this](https://github.com/An0nimia/DeezloaderAn0n_bot/blob/master/README.md)

**Comment by An0nimia** [comment]
What buttons are you talking about?
