### ISSUE TITLE
Detailed documentation

### ISSUE THREAD

**Issue by adoboligh1** [An0nimia/DeezloaderAn0n_bot#29]
this is a nice source code i tried using the documentaton but my bot never worked

**Comment by Mushebeq** [comment]
Send me the screenshot of your settings.ini file. Make sure to hide tokens

**Comment by adoboligh1** [comment]
Okay

**Comment by adoboligh1** [comment]
> Send me the screenshot of your settings.ini file. Make sure to hide tokens

I Just realised the problem and it was from my settings.ini files and nowit says "ModuleNotFoundError: No module named 'telegram' "

**Comment by Mushebeq** [comment]
`pip3 install python-telegram-bot`

**Comment by adoboligh1** [comment]
> `pip3 install python-telegram-bot`
How long will it take for the bot to work

**Comment by adoboligh1** [comment]
Last login: Fri Jun 12 10:46:39 2020 from 154.160.20.213
root@ubuntu-s-6vcpu-16gb-nyc1-01:~# cd /root/DeezloaderAn0n_bot
root@ubuntu-s-6vcpu-16gb-nyc1-01:~/DeezloaderAn0n_bot# python3 dwsongs-normal.py
1): Free
2): Strict
Choose: 1
Bot started
this was what i got

**Comment by Mushebeq** [comment]
The bot is now working. send /start command to your bot

**Comment by adoboligh1** [comment]
[https://i.ibb.co/rsb6scH/Screenshot-2020-06-12-at-10-52-01.png](url)

Thats the screenshot

**Comment by Mushebeq** [comment]
Edit [this](https://github.com/An0nimia/DeezloaderAn0n_bot/blob/01b2b77ab411e4359b11570cd93584227c9f945e/settings.py#L7) line with your telegram id.

**Comment by adoboligh1** [comment]
``

> Edit [this](https://github.com/An0nimia/DeezloaderAn0n_bot/blob/01b2b77ab411e4359b11570cd93584227c9f945e/settings.py#L7) line with your telegram id.

okay i will try again and see

**Comment by Mushebeq** [comment]
Contact me on telegram..my username is @killthenoise.

**Comment by adoboligh1** [comment]
> Contact me on telegram..my username is @Killthenoise.

Alright i will do it ASAP

**Comment by adoboligh1** [comment]
its now working but it only works when you send it a deezer link
