### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by RicardoAlex101** [An0nimia/DeezloaderAn0n_bot#31]
- MongoDB Data Base Supports For Saving Users ID 
- Support For Banning Users Using Their User ID
- Broadcast Support
- Support For Saving Songs In A Telegram Channel
**Reference:** https://github.com/odysseusmax/animated-lamp 
- Zip Support For Playlist Download

**Thanks For Your Amazing Code ;)**

**Comment by An0nimia** [comment]
The code is open source ;)
