### ISSUE TITLE
Too many Errors on log

### ISSUE THREAD

**Issue by Mushebeq** [An0nimia/DeezloaderAn0n_bot#34]
I'm getting a lot of error using the bot. I tried to fix one of them, but everytime i fix something i break something. Could you please fix this errors?
https://0bin.net/paste/SvPHlIYR#hwEinH2LeYHLK1dB32RO+qyTz9nXeMhfpSD-aTEMDJv

**Comment by An0nimia** [comment]
Please write here the log file, the link is expired.

**Comment by Mushebeq** [comment]
[dwsongs.log.txt](https://github.com/An0nimia/DeezloaderAn0n_bot/files/5146969/dwsongs.log.txt)

**Comment by An0nimia** [comment]
What happens if you use exactly the same code which is on GitHub?

**Comment by Mushebeq** [comment]
I'm using the same code as yours now, the only thing i changed is the default time (to 0.8).

**Comment by An0nimia** [comment]
@Mushebeq Your deezloader version which is?

**Comment by Mushebeq** [comment]
> @Mushebeq Your deezloader version which is?

Version: 2020.8.20

**Comment by An0nimia** [comment]
The shell show something?
