### ISSUE TITLE
link.tospotify.com The bot doesn't support this link 

### ISSUE THREAD

**Issue by profgenki** [An0nimia/DeezloaderAn0n_bot#37]
The bot doesn't support this links https://link.tospotify.com/E2VeJBHhybb https://deezer.page.link/YhQSurqCS4vgFnn27

**Comment by An0nimia** [comment]
@profgenki how did you get that link?

**Comment by profgenki** [comment]
In the latest versions of Spotify and deezer

**Comment by An0nimia** [comment]
@profgenki more specific what do you click for copy that link?

**Comment by profgenki** [comment]
https://x0.at/8D0.mp4

**Comment by profgenki** [comment]
https://x0.at/PRa.mp4

**Comment by An0nimia** [comment]
@profgenki I will add an implementation of this in the future, but I don't know when

**Comment by An0nimia** [comment]
@profgenki Update to the last version of Deezloader and copy the last code updated of dwsongs-nromal.py
