### ISSUE TITLE
Downloading directly to the server

### ISSUE THREAD

**Issue by 9Mad-Max5** [An0nimia/DeezloaderAn0n_bot#5]
Hi,

I try to establiche it to use this telegram bot just to send the audio file so my server.
So instead of deleting the files after sending it with telegram is just want so let it stick in the download folder and move it to my music directory.

**Comment by An0nimia** [comment]
@9Mad-Max5 The default output is the local dir/Songs, if you specify output when you call the function they will be stored in that directory, do I understand your question?

**Comment by 9Mad-Max5** [comment]
@An0nimia Hi youv'e getting it wright.
But after sending is as a audio which is pretty need it will be deleted on the server.
Unfortunally im not the python guy and struggeling to disable the sending aswell as the delete.
Could you help me out?

**Comment by An0nimia** [comment]
@9Mad-Max5 At the end of the script there is a for cicle inside while True cicle the only thing that you have to do is to delete that part of code inside that while True and write only sleep(8)
