### ISSUE TITLE
Lyrics at lower quality

### ISSUE THREAD

**Issue by lologolo** [An0nimia/DeezloaderAn0n_bot#6]
Can you add the possibility to add lirycs to lower quality songs?
Lyrics are only applied on FLAC files

**Comment by An0nimia** [comment]
@lologolo No also to 320 and others

**Comment by lologolo** [comment]
@An0nimia i tried alla format and only FLAC uses lyrics. 320 doesn't have yrics

**Comment by An0nimia** [comment]
@lologolo Try ? of xxxtentation
